### ISSUE TITLE
How did you make your site?

### ISSUE THREAD

**Issue by smac89** [tavianator/tavianator.com#1]
Is this gitbook?

**Comment by smac89** [comment]
Oh mdBook! Cool

**Comment by tavianator** [comment]
Yep, mdBook!  Maybe I'll make a README at some point, but the gist of it is:

- mdBook as the site generator
  - A [custom preprocessor](https://github.com/tavianator/tavianator.com/blob/main/preproc/src/main.rs) for easy FontAwesome icons
  - A [custom `<head>`](https://github.com/tavianator/tavianator.com/blob/main/theme/head.hbs) for [KaTeX](https://katex.org/) formatting
- Podman (basically Docker) for [deployment](https://github.com/tavianator/tavianator.com/blob/main/infra/blog/Dockerfile)
  - [cgit](https://github.com/tavianator/tavianator.com/blob/main/infra/cgit/Dockerfile) for browsing my git repos
  - Nginx for all the servers, with [Let's Encrypt](https://github.com/tavianator/tavianator.com/blob/main/infra/proxy/proxy.sh) on the root proxy

**Comment by edin-m** [comment]
@tavianator How did you make svg images/animations in [Ray/Bounding Box Intersections, Part 3: Boundaries](https://tavianator.com/2022/ray_box_boundary.html#fast-branchless-raybounding-box-intersections-part-3-boundaries)?

**Comment by tavianator** [comment]
> @tavianator How did you make svg images/animations in [Ray/Bounding Box Intersections, Part 3: Boundaries](https://tavianator.com/2022/ray_box_boundary.html#fast-branchless-raybounding-box-intersections-part-3-boundaries)?

I just wrote them by hand: https://github.com/tavianator/tavianator.com/blob/main/src/2022/ray_box_boundary.md#L59-L144
