### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by tavianator** [tavianator/tavianator.com#2]
As requested https://twitter.com/gpakosz/status/1477757249749757953?t=kzIeWJH6nq6dMu4poVPgYQ

**Comment by tavianator** [comment]
`mdbook-rss` depends on some "front matter" metadata in each post: https://gitlab.com/albalitz/mdbook-rss/-/tree/HEAD/#configuration-book-chapters-and-rss-items.  I could generate the infobar from it as well.

**Comment by Pat-Lafon** [comment]
Hello! I came along looking for exactly this(an rss feed) after reading https://tavianator.com/2023/bfs_3.0.html . Wanted to bump this issue to show continued interest in this.

**Comment by ChosunOne** [comment]
Adding support for an RSS feed as well!

**Comment by tavianator** [comment]
This is now done!

- https://tavianator.com/feed.atom
- https://tavianator.com/feed.json
- https://tavianator.com/feed.rss
